# Generated by Django 5.1.2 on 2024-11-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums_app', '0001_initial'),
        ('musicians_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('singer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicians_app.musician')),
            ],
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
